title: SANJAY KUMAR # your name (or website title) here
logo: "/images/instasize_190410160202.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <p><b> Email - 
   <a href="https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=me.sanjaykumar27@gmail.com"> - me.sanjaykumar27@gmail.com </a>
  </b> </p>
  
  <br><br>
  <a href="https://www.linkedin.com/in/sanjaymehra27"> - LinkedIn Profile </a>
  <br><br>
  <a href="https://www.hackerrank.com/sanjaymehra27"> - HackerRank Profile </a>
  <br><br>
  <a href="https://github.com/SanjayMehra-27"> - GitHub Profile </a>
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
